# API User
@host = http://localhost:3000/api/user
@id = 5bef699a96d9c51275f9100e
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZWYyZjc1MWRmNzk1MGEyYTMwMDdhYiIsImlhdCI6MTU0MjQwMTkwOX0.QDBcejPJvTwcF8ZA3YGUeyHKiOmmiMU4BTK1lrk-__4
GET {{host}}
###
POST {{host}}
content-type: application/json

{
  "name": "bob",
  "email": "bob@email.com",
  "password": "qwerty"
}
###
GET {{host}}/{{id}}
###
PATCH {{host}}/{{id}}
content-type: application/json

{
  "name": "lol",
  "email": "lol@email.com"
}
###
DELETE {{host}}/{{id}}
###
GET http://localhost:3000/api/me
Authorization: Bearer {{token}}
###
POST http://localhost:3000/api/login
content-type: application/json

{
  "email": "bob@email.com",
  "password": "qwerty"
}
